os: osx
osx_image: xcode10
language: objective-c
install: 
  - gem update cocoapods
before_script: 
  - pod lib lint --allow-warnings
  - swiftlint --strict
matrix:
  include:
    - env: NAME=Xcode DESTINATION="platform=iOS Simulator,name=iPhone 8"
    - env: NAME=SPM
script:
- |
  if [ "$NAME" = "Xcode" ]
  then
    xcodebuild test -project Crossroad.xcodeproj -scheme Crossroad -destination "${DESTINATION}"
  else
    swift test
  fi
