os: osx
osx_image: xcode10.2
language: objective-c
install: 
  - eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"
before_script: 
  - pod lib lint --allow-warnings
  - swiftlint --strict
matrix:
  include:
    - env: NAME=Xcode DESTINATION="platform=iOS Simulator,name=iPhone 8" SCHEME="Crossroad"
    - env: NAME=Xcode DESTINATION="platform=tvOS Simulator,name=Apple TV 4K" SCHEME="Crossroad-tvOS"
script:
- xcodebuild test -project Crossroad.xcodeproj -scheme "${SCHEME}" -destination "${DESTINATION}"
