os: osx
osx_image: xcode9.3
language: objective-c
before_script: 
  - pod lib lint --allow-warnings
  - swiftlint
matrix:
  include:
    - env: DESTINATION="platform=iOS Simulator,name=iPhone 8"
script:
- xcodebuild test -project Crossroad.xcodeproj -scheme Crossroad -destination "${DESTINATION}"
